Repository adopted-ember-addons/ember-cli-ifa, pull requests merged in 2019-11, with the labels that each got.

#57 Fix FastBoot support
  addon/utils/get-asset-map-data.js
  index.js
Labels: bug

#58 Replace `ember-cli-eslint` with regular ESLint
  package.json
  run-fastboot-tests.js
  yarn.lock
Labels: internal

#64 Add dependabot config file
  .dependabot/config.yml
Labels: internal

#65 Use prettier to format JS code
  .eslintrc.js
  .prettierrc.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  package.json
  run-fastboot-tests.js
  testem.js
  tests/acceptance/asset-map-test.js
  tests/dummy/app/app.js
  tests/dummy/app/initializers/fastboot/dom-helper-patches.js
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/unit/services/asset-map-test.js
  yarn.lock
Labels: internal

#68 Simplify acceptance test
  package.json
  tests/acceptance/asset-map-test.js
  tests/dummy/app/templates/application.hbs
  yarn.lock
Labels: internal

#73 Modernise and fix fastboot tests
  fastboot-server/server.js
  fastboot-tests/ember-cli-ifa-test.js
  package.json
  tests/fastboot/fastboot-test.js
  yarn.lock
Labels: internal

#79 Adjust `.npmignore` file
  .npmignore
Labels: internal

#80 Remove unused dependencies
  package.json
  yarn.lock
Labels: internal

#81 Drop support for Node 6
  .travis.yml
  package.json
Labels: breaking

#99 README: Fix spelling mistake
  README.md
Labels: documentation

#100 Show warning for missing `<meta>` tag
  addon/utils/get-asset-map-data.js
Labels: enhancement

#101 Simplify `assetMapString` condition
  addon/utils/get-asset-map-data.js
Labels: internal
